// Code generated by MockGen. DO NOT EDIT.
// Source: util.go
//
// Generated by this command:
//
//	mockgen -source=util.go -destination=mocks/util_mock.go
//

// Package mock_util is a generated GoMock package.
package mock_util
